### ISSUE TITLE
Coverage calculation includes read duplicates

### ISSUE THREAD

**Issue by vincent-hanlon** [mattsada/sspipe#15]
Coverage (for alignment_qc.pdf and others) is calculated as follows:

PF_READS_ALIGNED * MEAN_READ_LENGTH/GENOME_SIZE

I believe this means that duplicate reads are included for the coverage calculation, since they will be included in PF_READS_ALIGNED. This makes the coverage statistics somewhat misleading.

**Comment by mattssca** [comment]
I see your point. I could update the formula so that it indeed omits duplicated reads. Instead of using the `PF_READS_ALIGNED` metrics, the new coverage will be calculated using the `ESTIMATED_LIBRARY_SIZE` metrics from mdup .txt. 

If I understand these metrics correctly, this string represents the estimated number of unique molecules in the library based on PE duplications.

So with your comments in mind, coverage will be calculated as follow

`(ESTIMATED_LIBRARY_SIZE*MEAN_READ_LENGTH)/GENOME_SIZE`

We could also just subtract the number of duplications from the PF_READS_ALIGNED. In doing so, we end up with more reads compared to using the `ESTIMATED_LIBRARY_SIZE`

**For comparison:**
                        
option 1: `ERR1429090 ESTIMATED_LIBRARY_SIZE =  1 361 369`
option 2: `ERR1429090 DUPLICATIONS - PF_READS_ALIGNED = 1 446 632`

Calculated coverage
(old calculation, duplications included): `6.7 %`
option 1: `4.4%`
option 2: `4.7%`

Do think it's best to substitute the old calculation or should both be kept, is there any interest in looking at them both?

**Comment by vincent-hanlon** [comment]
I think that option 2 (multiplied by -1) is better than option 1. The estimated library size is the total number of unique molecules in the whole library: that is, including many molecules that were not sequenced. Without being 100% sure, I also think that these are molecules rather than reads. Each molecule represents two reads, so the correct way to calculate option 1 would be `estimated_library_size*2*read_length/genome_size`. But regardless, option 1 isn't quite the same thing as coverage. 

Option 2 is a reasonable way to calculate coverage. It's probably not the most representative for single cell libraries (we should exclude reads that map to sites with depth >2, or possibly depth >1 for low-coverage libraries), and it probably won't match BAIT or BreakpointR, but that's maybe ok.
